- name: restart nova-compute service
  service:
    name: nova-compute
    state: restarted

- name: restart neutron-linuxbridge-agent service
  service:
    name: neutron-linuxbridge-agent
    state: restarted
