- hosts: all
  roles:
    - common

- hosts: nested_hypervisors
  roles:
    - nested_hypervisor

- hosts: controllers
  roles:
    - controller
    - mysqldb
    - rabbitmq
    - memcached
    - etcd
    - keystone
    - glance
    - placement
    - nova
    - neutron
    - horizon

- hosts: compute_nodes
  roles:
    - compute
