- name: install neutron packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - neutron-server
    - neutron-plugin-ml2
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent

- name: add neutron configuration file
  template:
    dest: /etc/neutron/neutron.conf
    src: etc/neutron/neutron.conf.j2
    owner: root
    group: neutron
    mode: 0640
  notify:
    - restart neutron-server service

- name: add ml2 configuration file
  copy:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    src: etc/neutron/plugins/ml2/ml2_conf.ini
    owner: root
    group: neutron
    mode: 0644
  notify:
    - restart neutron-server service

- name: add ml2 linuxbridge agent configuration file
  template:
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    src: etc/neutron/plugins/ml2/linuxbridge_agent.ini
    owner: root
    group: neutron
    mode: 0644
  notify:
    - restart neutron-server service

- name: set neutron sysctls
  sysctl:
    name: "{{ item }}"
    state: present
    value: 1
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: modprobe br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: add DHCP agent file
  copy:
    dest: /etc/neutron/dhcp_agent.ini
    src: etc/neutron/dhcp_agent.ini
    owner: root
    group: neutron
    mode: 0644
  notify:
    - restart neutron-server service

- name: populate the keystone database
  command: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
  notify:
    - restart neutron-server service
    - restart neutron-linuxbridge-agent service
