- name: restart nova-api
  service:
    name: nova-api
    state: restarted

- name: restart nova-scheduler
  service:
    name: nova-scheduler
    state: restarted

- name: restart nova-conductor
  service:
    name: nova-conductor
    state: restarted

- name: restart nova-novncproxy
  service:
    name: nova-novncproxy
    state: restarted