- name: install mariadb server
  package:
    name: mariadb-server
    state: latest

- name: start and enable mariadb
  service:
    name: mariadb
    state: started
    enabled: yes

- name: install python mysql modules
  package:
    name: python-pymysql
    state: latest

# For idempotence, we first set a root password.
# Ignore errors, becausethe password may have already been set
# Then, we drop in a /root/.my.cnf
# See the official docs for more info:
# https://docs.ansible.com/ansible/latest/modules/mysql_user_module.html#mysql-user-module

# In an effort to make databases as complicated as reasonably possible,
# the current version of mariadb only permits auth via a unix socket
- name: set initial root password
  mysql_user: 
    name: root
    password: "{{ mariadb_root_pw }}"
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
  ignore_errors: true
  register: result

- name: add root my.cnf
  template:
    dest: /root/.my.cnf
    src: root/my.cnf
    owner: root
    group: root
    mode: 0600
  when: result is succeeded

- name: add OpenStack DB config file
  template:
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    src: etc/mysql/mariadb.conf.d/99-openstack.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mysqld
  register: os_config_file

- name: immediately restart mariadb after config change
  service:
    name: mysqld
    state: restarted
  when: os_config_file.changed

- name: drop anonymous user
  mysql_user:
    name: ''
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: localhost
    state: absent

# Create keystone user and database
- name: create keystone user
  mysql_user:
    name: keystone
    host: '%'
    password: "{{ keystone_db_pw }}"
    priv: 'keystone.*:ALL'
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: create keystone databases
  mysql_db:
    name: keystone
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

# Create glance user and database
- name: create glance user
  mysql_user:
    name: glance
    host: '%'
    password: "{{ glance_db_pw }}"
    priv: 'glance.*:ALL'
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: create glance database
  mysql_db:
    name: glance
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

# Create nova user and database
- name: create nova user
  mysql_user:
    name: nova
    host: '%'
    password: "{{ nova_db_pw }}"
    priv: 'nova_api.*:ALL/nova.*:ALL/nova_cell0.*:ALL'
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: create nova databases
  mysql_db:
    name: "{{ item }}"
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
  with_items:
    - nova_api
    - nova
    - nova_cell0

# Create neutron user and database
- name: create neutron user
  mysql_user:
    name: neutron
    host: '%'
    password: "{{ neutron_db_pw }}"
    priv: 'neutron.*:ALL'
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: create neutron databases
  mysql_db:
    name: "neutron"
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock