- name: partition data drive
  parted:
    device: /dev/sdb
    number: 1
    part_start: 0%
    part_end: 0%
    align: optimal
    part_type: primary
    label: gpt
    name: data
    state: present

- name: create filesystem
  filesystem:
    dev: /dev/sdb1
    fstype: ext4

- name: mount data to /var/lib/libvirt/images
  mount:
    path: /var/lib/libvirt/images
    src: /dev/sdb1
    fstype: ext4
    state: mounted

- name: install virtualization packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - qemu-kvm
    - libvirt-bin

- name: enable libvirt service
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: enable nested virtualization
  lineinfile:
    path: /etc/modprobe.d/kvm.conf
    line: 'options kvm_intel nested=1'
    create: true
    state: present
  notify: modprobe kvm

- name: add ISO directory
  file:
    path: /var/lib/libvirt/images/isos
    state: directory
    owner: root
    group: root
    mode: 0755

- name: add Ubuntu 18.04 ISO
  copy:
    dest: /var/lib/libvirt/images/isos/ubuntu-18.04.2-server-amd64.iso
    src: ubuntu-18.04.2-server-amd64.iso
    owner: root
    group: root
    mode: 0644