- name: set hostname
  hostname:
    name: "{{ inventory_hostname_short }}"

- name: add /etc/hosts file
  template:
    dest: /etc/hosts
    src: etc/hosts.j2
    owner: root
    group: root
    mode: 0644

- name: add systemd-timesyncd config
  copy:
    dest: /etc/systemd/timesyncd.conf
    src: etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  notify: reload systemd-timesyncd

# aptitude is needed to use generic package module
- name: install aptitude package
  package:
    name: 'aptitude'
    state: latest

- name: Add apt key for cloud archives
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 391A9AA2147192839E9DB0315EDB1B62EC4926EA

- name: add Stein cloud-archive repository
  apt_repository:
    repo: deb http://ubuntu-cloud.archive.canonical.com/ubuntu bionic-updates/stein main
    state: present
    update_cache: yes

- name: update all packages
  package:
    name: '*'
    state: latest

- name: install python-openstackclient
  package:
    name: python-openstackclient
    state: latest