- name: install keystone packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - keystone
    - apache2
    - libapache2-mod-wsgi-py3

- name: add keystone config file
  template:
    dest: /etc/keystone/keystone.conf
    src: etc/keystone/keystone.conf
    owner: keystone
    group: keystone
    mode: 0644

- name: sync keystone DB
  command: su -s /bin/sh -c "keystone-manage db_sync" keystone

- name: perform fernet setup
  command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone

- name: perform credential setup
  command: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone

- name: bootstrap the identity service
  command: "keystone-manage bootstrap --bootstrap-password {{ keystone_admin_pw }} \
    --bootstrap-admin-url http://{{ inventory_hostname }}:5000/v3/ \
    --bootstrap-internal-url http://{{ inventory_hostname }}:5000/v3/ \
    --bootstrap-public-url http://{{ inventory_hostname }}:5000/v3/ \
    --bootstrap-region-id RegionOne"

- name: set Apache ServerName
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^ServerName.*'
    line: "ServerName {{ ansible_host }}"
    state: present
  notify: reload apache2

# Sets a fact with info about the cloud to use
# See: https://github.com/ansible/ansible/issues/19621
- name: set OS auth info
  set_fact:
    os_cloud_info:
      auth:
        auth_url: "http://{{ inventory_hostname }}:5000/v3"
        username: admin
        password: "{{ keystone_admin_pw }}"
        project_name: admin
        os_user_domain_name: default
        os_project_domain_name: default
      auth_type: password
      region_name: RegionOne
      auth_version: 3
      compute_api_version: 3

- name: add keystone service project
  os_project:
    cloud: "{{ os_cloud_info }}"
    name: service
    description: "Project for OS Services"
    domain: default

# Add keystone config for glance
- name: create glance keystone user
  os_user:
    cloud: "{{ os_cloud_info }}"
    name: glance
    domain: default
    password: "{{ glance_keystone_pw }}"

- name: add admin role to glance user and service project
  os_user_role:
    cloud: "{{ os_cloud_info }}"
    user: glance
    project: service
    role: admin

- name: add glance service
  os_keystone_service:
    cloud: "{{ os_cloud_info }}"
    name: glance
    description: "Openstack Image Service"
    service_type: image

- name: add glance service endpoints
  os_keystone_endpoint:
    cloud: "{{ os_cloud_info }}"
    service: glance
    endpoint_interface: "{{ item }}"
    url: "http://{{ inventory_hostname }}:9292"
    region: RegionOne
  with_items:
    - public
    - internal
    - admin

# Add keystone config for nova
- name: create nova keystone user
  os_user:
    cloud: "{{ os_cloud_info }}"
    name: nova
    domain: default
    password: "{{ nova_keystone_pw }}"

- name: add admin role to nova user and service project
  os_user_role:
    cloud: "{{ os_cloud_info }}"
    user: nova
    project: service
    role: admin

- name: add nova service
  os_keystone_service:
    cloud: "{{ os_cloud_info }}"
    name: nova
    description: "Openstack Compute Service"
    service_type: compute

- name: add nova service endpoints
  os_keystone_endpoint:
    cloud: "{{ os_cloud_info }}"
    service: nova
    endpoint_interface: "{{ item }}"
    url: "http://{{ inventory_hostname }}:8774/v2.1"
    region: RegionOne
  with_items:
    - public
    - internal
    - admin

# Add keystone config for neutron
- name: create neutron keystone user
  os_user:
    cloud: "{{ os_cloud_info }}"
    name: neutron
    domain: default
    password: "{{ neutron_keystone_pw }}"

- name: add admin role to neutron user and service project
  os_user_role:
    cloud: "{{ os_cloud_info }}"
    user: neutron
    project: service
    role: admin

- name: add neutron service
  os_keystone_service:
    cloud: "{{ os_cloud_info }}"
    name: neutron
    description: "Openstack Network Service"
    service_type: network

- name: add neutron service endpoints
  os_keystone_endpoint:
    cloud: "{{ os_cloud_info }}"
    service: neutron
    endpoint_interface: "{{ item }}"
    url: "http://{{ inventory_hostname }}:9696"
    region: RegionOne
  with_items:
    - public
    - internal
    - admin

# Add keystone config for placement
- name: create placement keystone user
  os_user:
    cloud: "{{ os_cloud_info }}"
    name: placement
    domain: default
    password: "{{ placement_keystone_pw }}"

- name: add admin role to placement user and service project
  os_user_role:
    cloud: "{{ os_cloud_info }}"
    user: placement
    project: service
    role: admin

- name: add placement service
  os_keystone_service:
    cloud: "{{ os_cloud_info }}"
    name: placement
    description: "Placement API"
    service_type: placement

- name: add placement service endpoints
  os_keystone_endpoint:
    cloud: "{{ os_cloud_info }}"
    service: placement
    endpoint_interface: "{{ item }}"
    url: "http://{{ inventory_hostname }}:8778"
    region: RegionOne
  with_items:
    - public
    - internal
    - admin
