- name: install keystone packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - keystone
    - apache2
    - libapache2-mod-wsgi-py3

- name: add keystone config file
  template:
    dest: /etc/keystone/keystone.conf
    src: etc/keystone/keystone.conf
    owner: root
    group: root
    mode: 0644

- name: sync keystone DB
  command: su -s /bin/sh -c "keystone-manage db_sync" keystone

- name: perform fernet setup
  command: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone

- name: perform credential setup
  command: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone

- name: bootstrap the identity service
  command: "keystone-manage bootstrap --bootstrap-password {{ keystone_admin_pw }} \
            --bootstrap-admin-url http://{{ inventory_hostname }}:35357/v3/ \
            --bootstrap-internal-url http://{{ inventory_hostname }}:5000/v3/ \
            --bootstrap-public-url http://{{ inventory_hostname }}:5000/v3/ \
            --bootstrap-region-id RegionOne"

- name: set Apache ServerName
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^ServerName.*'
    line: "ServerName {{ ansible_host }}"
    state: present
  notify: reload apache2

# Add keystone config for glance
- name: get authentication token
  tags: dev
  os_auth:
    auth:
      auth_url: "http://{{ inventory_hostname }}:5000/v3"
      username: admin
      password: "{{ keystone_admin_pw }}"
      project_name: admin
      os_user_domain_name: Default
      os_project_domain_name: Default
